# fly.toml app configuration file generated for cracked-leetcode-junkie-bot on 2025-10-24T10:22:50Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'cracked-leetcode-junkie-bot'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile'

[env]
  LOG_LEVEL = 'info'

[[vm]]
  size = 'shared-cpu-1x'

[mounts]
  source = "bot_data"
  destination = "/app/data"
